### gate way to Eureka
GET http://localhost:8210/auth/test


### GET JWT token  gateway port : 8210
GET http://admin:1234@localhost:8210/auth/jwt?id=test

### Jwt 인가 받는거
GET http://admin:1234@localhost:8210/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IiIsImlhdCI6MTczNDk5OTc5NiwiZXhwIjoxNzM1MDAzMzk2fQ.t1m1ixukq4LYZfnd8QFXrTNZ1XD96gtk8Ny-BdQYhpE

