### gate way to Eureka
GET http://localhost:8210/auth/test


### GET JWT token  gateway port : 8210
GET http://admin:1234@localhost:8210/auth/jwt?id=test

### Jwt 인가 받는거
GET http://admin:1234@localhost:8210/auth/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6InRlc3QiLCJpYXQiOjE3MzUwMjIxOTIsImV4cCI6MTczNTAyNTc5Mn0.4msiefppqh-fLdChvYXcBDPjtYZwdtn7i_QTvji1UxbDJxDPZh90PvM56h2FsX_JmBlv1ocyzt3LTBNf9CD-pg

